version: '3.5'

services:
  ingest:
    build: .
    container_name: open-360-ingest-server
    environment:
      - PORT=4001
    ports:
      - "4001:4001"
    networks:
      ingest-network:

networks:
  ingest-network:
    name: "ingest-network"