version: '3.5'

services:
  ingest:
    build: .
    container_name: open-360-ingest-server
    environment:
      - RTMPPORT=1935
      - HTTPPORT=8000
    ports:
      - "8000:8000"
      - "1935:1935"
    #DEBUG VARIABLES
    #  - "9229:9229"
    #command:
    #  - node
    #  - "--inspect-brk=0.0.0.0"
    #  - "main.js"
    networks:
      ingest-network:
      api-network:
      ingest-memory:
    volumes:
      - "/usr/src/open360/video_database:/app/video_database"

  ingest-redis:
    image: redis
    container_name: open360-redis-ingest
    hostname: open360-redis-ingest
    volumes:
      - "/usr/src/open360/ingest_data:/data"
      - "/usr/src/open360/redis.conf:/usr/local/etc/redis/redis.conf"
    networks:
      ingest-memory:

networks:
  ingest-memory:
  ingest-network:
    external: true
    name: "open360-ingest-network"
  api-network:
    external: true
    name: "open360-api-network"